### ISSUE TITLE
Database (Required Changes)

### ISSUE THREAD

**Issue by daniielf** [DITTeamProject/Movie_Rental_Management_System#19]
Customer:
  -Must not accept NULL username/password/email.
  -Add Birthday row.

Movie:
  -Add "age-required" row.
  -Add "Stars" row. (Rating)

(Customer is allowed to Rent the same movie several times--)

Transaction:
  -Add "Movie Name" row (So user can check it from "Transaction" page)

**Comment by Jamesxu182** [comment]
I don't think so.
